#pulling flask image from ecr to establish connection with the database and run the application

version: "3.8"

services:
  web:
    image: 982081079659.dkr.ecr.us-east-1.amazonaws.com/flask-mysql:latest
    ports:
      - "5002:5002"
    depends_on:
      - mydb

  mydb:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
